name: Test

on: push

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2.4.0

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node (uses version from .nvmrc)
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Node dependencies
        run: npm ci --no-audit --no-optional

      - name: Test packages
        run: npm run test

      - name: Keep artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage
          path: coverage
